Task: |
  Query the UniProt database to find all reviewed (Swiss-Prot) proteins from Escherichia coli (strain K12) that are annotated with the Protein name "transmembrane". 
  
  Save the list of their UniProt accession numbers to `<r></r>/a3d_modb_retrieval.json`.

  Output example format:
  ```json
  [
    "P0A8T7",
    "P0A8T8",
    "P0A8T9",
    ...
  ]
  ```

  All intermediate results should be saved to `<t></t>/a3d_modb_retrieval`

Verifier:
  a3d_modb_retrieval

