Task: |
    Review the published materials corresponding to the NCBI Biosample ERS1713185 and SRS4889584, collect host information metadata, and extract dietary information of host animals from databases such as MammalDIET, and so on.

    Saving the results to `<r></r>/amdb_extract.csv`.

    Output format (for reference only):
    Sample Accesion,Host,Diet
    ERS1713185,Capra hircus,Herbivore
    SRS4889584,N/A,N/A

    All intermediate results should be saved in `<t></t>/amdb_extract` directory.

Verifier:
    amdb_extract
