Task: |

  Process quality control and genomic mapping of the the raw sequencing data located at `benchmark/dataset/ASMdb/rna_seq/SRR942022_1.fastq`.

  Using fastp with default parameters.

  The reference genome located at `benchmark/dataset/ASMdb/ref/TAIR10_chr_all.fas`.

  Converting the alignment output into BAM format and perform coordinate-based sorting.

  Saving the final bam file in `<r></r>/asmdb_refinement_2.bam`

  All intermediate code generated during execution, downloaded files, and temporary results must be stored in `<t></t>/asmdb_refinement_2/`

Verifier:
  asmdb_refinement_2