Task: |
  Identify candidate genomic sites for Allele-Specific Methylation (ASM) analysis.
  
  You are provided with a BED file containing methylation information for individual cytosine sites `benchmark/dataset/ASMdb/toy_bed/mini_test.bed`. Your task is to filter this dataset to retain only "partially methylated" sites which serve as valid candidates for haplotype-dependent ASM identification. 
  
  Retain only the sites with intermediate methylation levels (0.1 <= Methylation Level <= 0.9).

  Saving the filtered bed file in `<r></r>/asmdb_refinement_1.bed`

  All intermediate code generated during execution, downloaded files, and temporary results must be stored in `<t></t>/asmdb_refinement_1/`

Verifier:
  asmdb_refinement_1