Task: |
  Based on the paper content in the file `benchmark/dataset/BioKA/paper_content.md`, retrieve the biomarker. 
  
  Extract the `biomarkerName` (abbreviation name), `biomarkerType` (protein, gene, or, others ...), `curated_disease_name`, and `biomarkerUsage` (must be one of diagnosis, prediction, therapeutic, prognosis, monitoring) for each biomarker and save them into a CSV file `<r></r>/bioka_extract.csv` with the headers `biomarkerName`, `biomarkerType`, `curated_disease_name`, and `biomarkerUsage`.
  

  Ouput example for reference:
  ```
  biomarkerName,biomarkerType,curated_disease_name,biomarkerUsage
  ```

  All intermediate code generated during execution, downloaded files, and temporary results must be stored in `<t></t>/bioka_extract/`

Verifier:
  bioka_extract