Task: |
  Based on the CellMarker file `benchmark/dataset/CancerSCEM/CellMarker.csv`, annoting the cell type `benchmark/dataset/CancerSCEM/cell_1.txt`. 
  
  Types include CD4+ Tcm, CD4+ Tem,CD8+ effector T cells, CD8+ naive T cells, CD8+ Tcm, CD8+ Tem, Dendritic cells, Endothelial cells, Fibroblasts, Macrophages, Malignant cells, Monocytes, NK cells, Plasma cells, Tregs, Unassigned. 
  
  Saving the result tpye into `<r></r>/cancerscem_annotate.json`.

  Output format:
  {
    "cell_1": "CD4+ Tcm"
  }

  All intermediate results should be save in `<t></t>/cancerscem_annotate` directory.

Verifier:
  cancerscem_annotate