  Task: |
    Given a csv file `benchmark/dataset/CellSTAR/cellstar_integration.csv` containing basic metadata of single-cell RNA-seq samples, including species, tissue, and cell type information.
  
    Standardizing species, tissues, and cell types with taxonomy, Uberon and the Cell Ontology, respectively.

    Saving the standardized metadata in `<r></r>/cellstar_integration.csv`.

    Output format (for reference):
    species,tissue,cell type
    axolotl,bladder,acinic cell
    African malaria mosquito,haemolymph,adipocyte
    ...

    All intermediate files should be saved in the `<t></t>/cellstar_integration` directory.

  Verifier:
    cellstar_integration