Task: |
  In genomic studies, datasets are often aligned to different reference genome builds (e.g., GRCh37/hg19 vs. GRCh38/hg38). 


  Given `benchmark/dataset/COLOCdb/GCST90000064_buildGRCh37.tsv` file, converting the genomic coordinates of the variants in the input file to the GRCh38 reference build. Skip the variants that cannot be successfully converted.

  Saving the converted results in a new file named `<r></r>/colocdb_refinement.tsv`.

  Output format (for reference):
  variant_id	MarkerName	effect_allele	other_allele	effect_allele_frequency	FreqSE	MinFreq	MaxFreq	beta	standard_error	p_value	Direction	HetISq	HetChiSq	HetDf	HetPVal	n	chromosome	base_pair_location
  rs75333668	1:762320	t	c	0.0031	0.0026	0.0009	0.006	NA	NA	0.624	+-	66	2.941	1	0.08636	644545	1	762320

  All intermediate steps should be saved in `<t></t>/colocdb_refinement` directory.

Verifier: 
  colocdb_refinement
