Task: |
  Process the provided CDS sequences in `benchmark/dataset/CompoDynamics/GCF_009428885.1_ASM942888v1_cds_from_genomic.fna`. 
  
  Filter out sequences that meet any of the following criteria: 1) length is not a multiple of 3; 2) does not start with an "ATG" codon; 3) does not end with a standard stop codon ("TAA", "TAG", or "TGA"); 4) contains an internal stop codon. 
  
  Save the remaining valid sequences to `<r></r>/compodynamics_integration.fna`.

  All temp data should be save in `<t></t>/compodynamics_integration`.

Verifier:
  compodynamics_integration