Task: |
  Calculate the genome-wide GC content for sequence from gene Accession Number NZ_WHYS01000010.1. 

  This should be done by computing a weighted average of the GC content of all individual CDS features. 

  The weight for each CDS is its length. Use the provided genome sequence `benchmark/dataset/CompoDynamics/GCF_009428885.1_ASM942888v1_cds_from_genomic.fna` and corresponding annotation file `benchmark/dataset/CompoDynamics/GCF_009428885.1_ASM942888v1_genomic.gff`. 

  Save the final calculated numeric value to `<r></r>/compodynamics_annotate.txt`.

  Output format example:
  0.5678

  All temp data should be save in `<t></t>/compodynamics_annotate`.

Verifier:
  compodynamics_annotate