Task: |
  There are two NCBI GEO dataset GSE153428 and GSE154769. 

  The NCBI GEO attachment files are located at  `benchmark/dataset/COVID-19/GSE153428` and `benchmark/dataset/COVID-19/GSE154769`.

  From this two dataset, find the Affymetrix microarray data and extract the express matrix from corresponding series_matrix file.

  And then, standardize the series matrix by mapping the probe IDs to HGNC Gene Symbols.
    
  Save the final processed matrix (rows as HGNC Gene Symbols, columns as GEO Accessions) to `<r></r>/covid_19_integration.csv`.

  Ouput format requirements (for reference only):
  ,GSM4644121,GSM4644122,GSM4644123,GSM4644124,GSM4644125,....
  "1-172,CRYAA",3.97,4.05,4.17,3.92,3.86,4.17,4.03,3.38,4.07,4.09,4.31,4.05
  "1-8D,IFITM2",12.68,13.8,12.93,16.09,16.88,16.88,16.17,16.75,16.92,16.01,16.68,16.9
  1-O,7.33,7.675,7.789999999999999,6.99,7.28,6.94,6.835,7.36,7.449999999999999,6.695,6.92,7.385
  ...

  All temp data should be save in `<t></t>/covid_19_integration`.

Verifier:
  covid_19_integration
  