Task: |
  For given covalent protein-ligand (cP-L) complexes, perform data enrichment and structural property calculations. 

  The pdb ids are given in the file `benchmark/dataset/CovPDB/cov_pdb_ids.json`, and corresponding structures are located in the directory `benchmark/dataset/CovPDB/complex_structures`.
  
  Retrieve experimental metadata from the PDB, specifically the structure determination method, resolution, and binding affinity (BindingDB). 
    
  Calculate the total Solvent Accessible Surface Area (SASA) for the complex structure. 
  
  Saving the annotated results as a csv file `<r></r>/covpdb_integration_complex.csv`.  
  
  # Output CSV Format for Complex (For Reference)
  index, PDB_ID, Method, Resolution, Affinity, SASA
  0, ABCD, X-RAY DIFFRACTION, 2.0,IC50 50 nM, 150.5
  0, EGFD, X-RAY DIFFRACTION, 2.0,N/A, 150.5
  ...

  # Intermediate Results
  All intermediate files generated should be saved in the directly `<t></t>/covpdb_integration`
  
Verifier: covpdb_integration


