Task: |
  Given a pdf content file `benchmark/dataset/CovPDB/pdf_content.md`. 
  
  Determining the covalent bonding mechanisms based on the given paper. 
  
  The mechanisms must be one of: Aziridine Opening; Beta-Lactam Addition; Borylation; Composite Reaction; Cyclohemiaminoacetalization; Disulfide Formation; Epoxide Opening; Hemiaminalization; Hemi(thio)acetalization; Imidazolidinone Opening; Imine Condensation; Lactone Addition; Michael Addition; Nucleophilic Acyl Substitution; Nucleophilic Addition to a Double Bond; Nucleophilic Addition to a Triple Bond; Nucleophilic Aliphatic Subsititution; Nucleophilic Aromatic Substitution; Phosphorylation; Ring Opening; Sulfonylation

  Saving the mechanisms into `<r></r>/covpdb_annotate.txt`.  
  
  # Output Format (For Reference)
  Sulfonylation

  # Intermediate Results
  All intermediate files generated should be saved in the directly `<t></t>/covpdb_annotate`

Verifier:
  covpdb_annotate