Task: |
  Query the Protein Data Bank (PDB) database. 
  
  Finding high-quality covalent protein-ligand complexes released between 2018-10-01T00:00:00Z and 2018-10-07T00:00:00Z. 
  
  Here, covelatent complexes are protein-ligand structures that binding with a covalent bond (distance threshold typically <= 2.0 Å between protien and ligand). 
  
  You should only keep structures with a resolution ≤ 2.5 Å. 
  
  Remove entries where the ligand is a known artifact (refer to the BioLiP artifact file in the path `benchmark/dataset/CovPDB/ligand_list`). 
    
  Saving the filtered pdb id list to the file `<r></r>/cov_pdb_retrieval.json`.

  # Intermediate Results
  All intermediate files generated should be saved in the directly `<t></t>/covpdb_retrieval`
  
Verifier: covpdb_retrieval