Task: |
  Given a pair-ended RNA-seq data in the directory `benchmark/dataset/CyanoOmicsDB/toy_srr`.

  Align them to the Synechocystis sp. PCC 6803 reference genome GCF_000009725.1 (`benchmark/dataset/CyanoOmicsDB/ncbi_dataset/data/GCF_000009725.1`). 

  Quantify gene-level raw read counts.

  Saving result to `<r></r>/cyanoomicsdb_annotate_2.txt`

  Output example format (for reference):
  ```
  SGL_RS01258	51
  SGL_RS00455	4
  SGL_RS05634	4
  ...
  ```

Verifier:
  cyanoomicsdb_annotate_2