Task: |
  Extract basic information for each gene from the annotation GFF file `benchmark/dataset/CyanoOmicsDB/ncbi_dataset/data/GCF_000009725.1/demo_genomic.gff`, including locus tags, gene symbols, genomic coordinates, protein ID, and product. 
  
  Then, for each protein-coding gene, integrate the Pfam accessions from InterProScan. The protein sequence as saved in `benchmark/dataset/CyanoOmicsDB/ncbi_dataset/data/GCF_000009725.1/protein.faa`.
  
  Finally, aggregate the extracted gene information and functional annotations into a comprehensive master TSV file `<r></r>/cyanoomicsdb_annotate_1.tsv`.

  All temp data should be save in `<t></t>/cyanoomicsdb`.

  The reference format for the output file:
  Locus_Tag       Symbol  Old_Locus_Tag   Location        Protein_ID      Product      Pfam
  SGL_RS01970     -       -       NC_005232.1:77988-78551(+)      WP_223211257.1  hypothetical protein      PF01497
  SGL_RS01975     -       -       NC_005232.1:78616-78828(-)      WP_011153842.1  hypothetical protein      PF11741;PF07715;PF00593
  SGL_RS01980     -       -       NC_005232.1:78981-79160(+)      WP_011153843.1  hypothetical protein      PF12833

  # Intermediate Results
  All intermediate files generated should be saved in the directly `<t></t>/cyanoomicsdb_annotate_1`

Verifier:
  cyanoomicsdb_annotate_1 