Task: |
  Reviewing the three drug-drug interactions description in the file `benchmark/dataset/DDInter/DDI.txt` and classified them into different risk levels (Major, Moderate, Minor, and Unknown). 
  
  Generally, Major interactions were highly clinically significant and the drug combinations should be strictly avoided; Moderate interactions may result in exacerbation of the disease of the patient and/or change in therapy; Minor interactions were minimally clinically significant and usually they do not require changes in therapy; Unknown interactions meant that the interaction description was unavailable or incomplete.
  
  Finially, saving the classification list into file <r></r>/ddinter_annotate_1.json.

  Output format  (for reference):
  [risk_level_1, risk_level_2, ...]

  All intermediate results should be save in `<t></t>/ddinter_annotate_1` directory.

Verifier:
  ddinter_annotate_1