Task: |
  For small-molecule drug entry in `benchmark/dataset/DDInter/integration_2.txt`, collecting the Anatomical Therapeutic Chemical (ATC) code.
 
  Additionally, annotating each drug with basic chemical information, including molecular formula, molecular weight, IUPAC name, InChI, InChIKey, and canonical SMILES. If none applicable values, using N/A.
  
  Saving the results to `<r></r>/ddinter_integration_2.csv`
  
  The output result should following the format (for reference):
  drug,ATC,formula,IUPAC,InChIKey,SMILES
  drug_1,N/A,formula_1,IUPAC_1,InChIKey_1,SMILES_1
  drug_2,ATC_2,formula_2,N/A,InChIKey_2,SMILES_2
  drug_3,ATC_3,N/A,IUPAC_3,InChIKey_3,SMILES_3

  All intermediate results should be save in `<t></t>/ddinter_integration_2` directory.

Verifier:
  ddinter_integration_2