Task: |
  Query DrugBank to obtain generic names and brand names for drug in `benchmark/dataset/DDInter/integration_1.txt`.

  Saving the results to `<r></r>/ddinter_integration_1.csv`
  
  The output result should following the format (for reference):
  query_name,generic_name,brand_name
  name_1,generic_name_1,brand_name_1
  name_2,generic_name_2,brand_name_2
  name_3,generic_name_3,brand_name_3

  All intermediate results should be save in `<t></t>/ddinter_integration_1` directory.

Verifier:
  ddinter_integration_1
