Task: |
  Search the SRA database for "Homo sapiens" datasets with a "miRNA-Seq" library strategy between 2021.10.01 and 2021.10.05. 
  
  Retrieve the accession numbers and sort them alphabetically. 
  
  Save the accession numbers as a list to a json file named `<r></r>/diana_mited_retrieval.json`

  Output format (for reference):
  [
  'SRRXXXXXXX',
  'SRXXXXXXXX',
  ...
  ]

  All intermediate files should be saved in the `<t></t>/diana_mited_retrieval` directory.

Verifier:
  diana_mited_retrieval