Task: |
  Given a small RNA sequencing data `benchmark/dataset/DIANA-miTED/sample.100k.fastq.gz`.

  Please first perform a quality control and adapter trimming on the raw reads, then align the preprocessed reads to the human reference genome (GRCh38, chromosome 22) provided in `benchmark/dataset/DIANA-miTED/chr22.fa`
  
  Then quantify miRNA expression levels with miRNA annotations from miRBase v22 `benchmark/dataset/DIANA-miTED/miRBase_v22`.

  Finally, calculating the proportion of preprocessed reads that are successfully assigned to known miRNAs, and save the ratio in `<r></r>/diana_mited_refinement.txt`.

  Output format (for reference):
  50.5%

  All intermediate files should be saved in the `<t></t>/diana_mited_refinement` directory.

Verifier:
  diana_mited_refinement