Task: |
  Given a sparse matrix representing single-cell data in MatrixMarket format. 
  
  The data is provided in three files: `benchmark/dataset/DISCO/refinement/matrix.mtx`, `benchmark/dataset/DISCO/refinement/features.tsv`, and `benchmark/dataset/DISCO/refinement/barcodes.tsv`. 
  
  Assemble them into a single sparse matrix object with appropriate row and column names, and then save this object into a single file in RDS format at `<r></r>/disco_refinement.rds`.

  All intermediate results should be save in `<t></t>/disco_refinement` directory.

Verifier:
  disco_refinement