Task: |  
  Given a list of smiles in `benchmark/dataset/FusionNeoAntigen/dock/smiles.txt`.

  Identify the smiles have highest vina affinity to protein `benchmark/dataset/FusionNeoAntigen/dock/1a1e_protein.pdb`.
  
  Docking pocket and size are listed in `benchmark/dataset/FusionNeoAntigen/dock/pocket_config.txt`.
  
  Save the final smiles `<r></r>/fusionneoantigen_annotate_2.txt`. 

  Output example for reference:
  ```
  cccccc
  ```
  
  All intermediate files generated during the extraction process should be stored in `<t></t>/fusionneoantigen_annotate_2/`.

Verifier: 
  fusionneoantigen_annotate_2