Task: |
  Given a list NCBI GEO Sample accession number ``, identifying and filtering for paired-end 16S rRNA SRA raw sequencing data.

  Saving the accession number of identifier 16S rRNA SRA raw sequencing runs to `<r></r>/mbodymap_integration.json`

  Output example for reference:
  ```
  [
    "SRR1",
    "SRR2"
  ]
  ```

  All temp data should be save in `<t></t>/mbodymap_integration`.

Verifier:
  mbodymap_integration