Task: |
  Identify high-quality RNA-seq Runs from three Runs in `benchmark/dataset/MetazExp/toy_srr1`, `benchmark/dataset/MetazExp/toy_srr2`, and `benchmark/dataset/MetazExp/toy_srr3`.

  High-quality RNA-seq Runs should meet all of the following criteria: (i) Paired-end sequencing; (ii) Read length ≥ 100 bp; (iii) Uniquely mapped read rate ≥ 50% for the reference genome `benchmark/dataset/MetazExp/ncbi_dataset/data/GCF_001039355.2/GCF_001039355.2_LinAna2.0_genomic.fna`. 
  
  Output the directory nname of high-qualit Runs to `<r></r>/metazexp_refinement.json`.

  Output Format (Only for Reference):
  [
    "toy_srr2"
  ]

  All temp data should be save in `<t></t>/etazexp_refinemen`.

Verifier:
  metazexp_refinement


