Task: |

  Perform a differential expression analysis for 6 DRX experiments in `benchmark/dataset/MetazExp/count`. 

  The basic information of the 6 DRX experiments is provided in `benchmark/dataset/MetazExp/sample_info.tsv`, which includes sample annotations specifying biological conditions (e.g., tissue, developmental stage) and study or batch identifiers.
  
  You must explicitly correct for study-specific batch effects by including the batch variable in the design formula (e.g., design = ~ batch + condition).
  
  Identify genes that are significantly differentially expressed in the target condition compared to all other conditions combined.

  Output the top 50 most significantly differentially expressed genes (ranked by adjusted p-value) to `<r></r>/metazexp_annotate.tsv`.
  
  Output Format (Only for Reference):
  gene_id	baseMean	log2FoldChange	lfcSE	stat	pvalue	padj
  FBgnxxxx	1254.66665476386	-2.87772911936465	0.87905045247991	-27.2422049305457	2.05567383473253e-163	3.25310384346423e-159
  FBgnyyyy	52136.516872705251	-4.730648430188	0.676023255336235	-24.3843527676287	2.50655533940541e-131	1.98331191230453e-127

  All temp data should be save in `<t></t>/metazexp_annotate`.


Verifier: 
  metazexp_annotate