Task: |
  There are 5 summary infromation about NCBI GEO datasets in the file `benchmark/dataset/MVIP/gds_test_data.txt`. 
  
  Based on these information, fetching out the high throughput sequencing dataset certainly related to virus infection. 
  
  Saving the keeped dataset idx list [index_1, index_2, ...] in <r></r>/mvip_annotate.tsv. 

  Output format example:
  [
    "1",
    "2",
    "3",
    "4",
    "5"
  ]

  All temp data should be save in `<t></t>/mvip_annotate`.

Verifier:
  mvip_annotate  
