Task: |
  Perform a Cox Proportional Hazards regression analysis on the provided `benchmark/dataset/OncoDB/rossi_dataset.csv`. 
  
  The model should use `week` as the duration column and `arrest` as the event column. 
  
  All other columns should be used as covariates. 
  
  Save the resulting regression summary table to a CSV file named `<r></r>/oncodb_annotate.csv`.

  Output example:
  ```
  covariate,coef,exp(coef),se(coef),coef lower 95%,coef upper 95%,exp(coef) lower 95%,exp(coef) upper 95%,cmp to,z,p,-log2(p)
  age,0.02,1.02,0.01,0.00,0.04,1.00,1.04,age,2.00,0.045,-4.47
  ``` 

  All intermidate results should be saved to `<t></t>/oncodb_annotate` directory.


Verifier:
  oncodb_annotate
