Task: |
  There are three paper contents `example_1.md, example_2.md, example_3.md` in the directory `benchmark/dataset/PCMDB`. 
  
  Filter out the paper research contain cell marker inferred through biological experiments, including GFP reporter systems, GUS gene reporter systems and western blotting. 
  
  Saving the keeped paper name list in the `<r></r>/pcmdb_extract_2.json`. 

  Output format: A JSON file with the following format:
  [name_1, name_2, ...] 

  Paper name must not contain suffix.

  All intermediate results should be save in `<t></t>pcmdb_extract_2` directory.

Verifier: 
  pcmdb_extract_2