Task: |
  Filter the provided SNP data in `benchmark/dataset/PGS-Depot/sample.vcf`. 

  The filtering criteria are: remove multi-allelic SNPs, remove SNPs with a minor allele frequency (MAF) less than 0.05, and remove SNPs with a genotype missing rate greater than 0.2. 
  
  Save the resulting filtered data as a VCF file named `<r></r>/pgs_depot_refinement.vcf`.

  All intermediate steps should be saved in `<t></t>/pgs_depot_refinement` directory.

Verifier:
  pgs_depot_refinement