Task: |
  Annotate the disease feature in the images in the directory `benchmark/dataset/PlantPAD`.

  Three features should be identified, including Color Of Diseases, Texture Of Diseases, and Leaf Morphology.
  
  Optional values for each features:
    Color Of Diseases: Black, Green, Yellow, Brown, Gray, Red Brown, White
    Texture Of Diseases: Spotted, Striped, Ring Spot, Netted Spot, Random Spot
    Leaf Morphology: Atrophy, Wilt, Rot, Burn, Perforation

  Saving the results to `<r></r>/plantpad_annotate.csv`.

  The output result should following the format (for reference):
  image,color,texture,morphology
  image_1.jpg,Black,Spotted,Atrophy
  image_2.jpg,Green,Striped,Wilt
  image_3.jpg,Yellow,Ring Spot,Rot

  All intermediate results should be save in `<t></t>/plantpad_annotate` directory.

Verifier:
  plantpad_annotate