Task: |
  Based on the paper content in `benchmark/dataset/PncsHub/paper_conent.md`. 
  
  Determine determine the Pathway Type of katG. There are eight types: FPE、FEA、Holins、MVs、SecA2、T7SS, ABC transptor, Unknown. 
  
  Saving the result to <r></r>/pncshub_annotate.txt.

  Output format example:
  FPE

  All temp data should be save in `<t></t>/pncshub_annotate`.

Verifier:
  pncshub_annotate