Task: |
  Given a list of collected traits in the `benchmark/dataset/RAVAR/reported_trails.json`.
  
  Standardizing the collected traits by deleting publication specific symbols and ambiguous language. So that we can unify the terminology, definitions, and classification of traits. 
  
  You should return a mapping dict save in the `<r></r>/ravar_refinement_1.json`. 
  
  The mapping dict should have the following format:
  {
    "original_trait_1": "standardized_trait_1",
    "original_trait_2": "standardized_trait_2",
    ...
  }

  All intermediate steps should be saved in `<t></t>/ravar_refinement_1` directory.

Verifier:
  ravar_refinement_1