Task: |
  According to the ontological information provided in the file `benchmark/dataset/RAVAR/trails_data.csv`,  categorizing the traits into the 3 distinct subcategories of material property, information entity, and material entity. 
  
  Saving the classification result as a json list [subcategory_1, subcategory_2, ...] to `<r></r>/ravar_refinement_2.json`.

  Ouput format example:
  ["material property", "information entity", "material entity"]

  All intermediate results should be saved in `<t></t>/ravar_refinement_2` directory.

Verifier:
  ravar_refinement_2