Task: |
  Find the intersections between the provided RBP binding sites (`benchmark/dataset/scAPAatlas/rbp_binding_sites.bed`) and a set of alternative polyadenylation (APA) regions (`benchmark/dataset/scAPAatlas/apa_regions.bed`). 
  
  Save the resulting intersected regions to `<r></r>/scapaatlas_annotate.bed`.

  Output example format:
  ```
  chr1  100	150	Peak_4557	841	.	8141.98552	454.85123	5120.84359	14278
  ```

  All intermediate results should be saved to `<t></t>/scapaatlas_annotate`

Verifier:
  scapaatlas_annotate