Task: |
  Standardize the heterogeneous cell type names from `benchmark/dataset/scQTLbase/test_data.json`. 
  
  Map these names to their canonical names based on the cellmarker name reference `benchmark/dataset/scQTLbase/CellMarker.json`. 
  
  Saving the converted names [converted_name_1, converted_name_2, ...] list into a json file `<r></r>/scqtlbase_refinement.json`.

  Output format example:
  ["T cell", "Mast cell", "Goblet cell"]

  All intermediate results should be saved in `<t></t>/scqtlbase_refinement` directory.

Verifier:
  scqtlbase_refinement