Task: |
  Classify gene entries in `benchmark/dataset/TF-Marker/tf_marker_entries.json` into five categories based on their functional description. 
  
  Read the paper conent file `benchmark/dataset/TF-Marker/paper_content.md`. 
  
  Classify the gene based on the paper content and following rules: (i) TF: TFs, which regulate the expression of markers. For example, FOXA1 (HNF3A) is a TF involved in embryonic development which plays an important role in cancer. Studies showed that FOXA1 could regulate the expression of cell marker PLOD2 by binding to its promoters, thereby affecting the occurrence and development of lung cancer; (ii) T Marker: markers, which are regulated by TFs. For example, TF POU5F1 controls the expression of marker genes (e.g. YES1, FGF4, UTF1 and ZFP206) involved in embryonic development. These genes are defined as Tmarker; (iii) I Marker: markers, which influence the activity of TFs. For example, Marker gene CD27 could activate PRDM1 and XBP1 by binding to TF CD70 on B cells. CD27 plays a role as I Marker; (iv) TFMarker: TFs, which play roles as markers. TFMarkers are usually cell/tissue-specific TFs and used as cell markers. For example, TF GATA3 is a definitive cell marker of breast cancer; and (v) TF Pmarker: TFs, which play roles as potential markers. For example, Becker et al. (12) found that TF LGR5 was a potential marker of intestinal stem cells in human .  
  
  Save the resulting categories list to `<r></r>/tf_marker_annotate.json`.

  Output format (for reference):
  [category_1, category_2, ...] 

  All intermediate results should be save in `<t></t>/tf_marker_annotate` directory.

Verifier:
  tf_marker_annotate