Task: |
  Given txt file containing biomarkers and their functions in the file `benchmark/dataset/TheMarker/biomarker.txt`. 
  
  According to the roles of these biomarkers played, labelled the biomarkers as pharmacodynamic biomarker (PDY), safety biomarker (SAF), monitoring biomarker (MOI), predictive biomarker (PRD) and surrogate endpoint (SUR). 
  
  Saving the classification list [label_1, label_2, ...] in the same sort as input file to json file `<r></r>/themarker_annotate.json`. 
  
  The output format example is as follows:
  ["PDY", "SAF", "MOI", "PRD", "SUR"]

  All intermediate results should be saved in `<t></t>/themarker_annotate` directory.

Verifier:
  themarker_annotate 