Task: |
  There are a list of possible single amino acid mutations for protein in `benchmark/dataset/VarEPS/4KMN.pdb`. The mutations are as listed in file `benchmark/dataset/VarEPS/mutation_list.txt`.
  
  Identify the most stable mutation among the list of possible mutations by saambe-3d. 

  Save the most stable mutation and its corresponding ΔΔG value to `<r></r>/most_stable_mutation.txt`.

  All temp data should be save in `<t></t>/vareps_annotation`.
  
  Output format (For Reference):
  A 415 Q T

Verifier:
  vareps_annotation