Task: |
  Extracting the mutation sites of Hepatitis B virus (HBV) from the provided pdf file `benchmark/dataset/ViMIC/12985_2021_Article_1493.pdf`.
  
  Saving the results into a json file `<r></r>/vimic_extract.json`.

  Result format reference:
  [
    "G130E",
    "L109R"
  ]

  All intermediate results should be saved in `<t></t>/vimic_extract` directory.

Verifier:
  vimic_extract