Task: |
  Extracting information for Biosamples (filter out those without SRA data) in BioProject PRJEB63303 and PRJNA1025946, including host, sample name, collection date and country.
  
  Saving the results into a csv file `<r></r>/zover_extract.csv`.

  Output format (for reference only):
  SampleName,Host,CollectionDate,Country,BioProject,BioSample
  Bat_throat,Eidolon helvum,2009/03,Ghana,ERP001979,SAMEA1573860

  All intermediate results should be saved in `<t></t>/zover_extract` directory.

Verifier:
  zover_extract