name: biomni_e1
channels:
  - hcc
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
  - conda-forge
  - bioconda
  - defaults
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch/
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - _py-xgboost-mutex=2.0
  - _r-mutex=1.0.0
  - adfr-suite=1.0
  - alsa-lib=1.2.8
  - argon2-cffi=25.1.0
  - argon2-cffi-bindings=25.1.0
  - astunparse=1.6.3
  - attrs=25.4.0
  - babel=2.17.0
  - bc=1.07.1
  - binutils_impl_linux-64=2.40
  - binutils_linux-64=2.40.0
  - biopython=1.86
  - bismark=0.25.1
  - blas=1.0
  - blast=2.16.0
  - bleach=6.3.0
  - blis=2.0
  - blosc=1.21.5
  - boltons=25.0.0
  - bowtie=1.3.1
  - bowtie2=2.5.4
  - brotli-bin=1.2.0
  - brotlicffi=1.2.0.0
  - bwidget=1.10.1
  - bzip2=1.0.8
  - c-ares=1.34.6
  - c-blosc2=2.14.4
  - ca-certificates=2026.1.4
  - cairo=1.18.4
  - certifi=2026.1.4
  - cffi=2.0.0
  - charset-normalizer=3.4.4
  - colorama=0.4.6
  - comm=0.2.3
  - conda=23.7.4
  - conda-package-handling=2.4.0
  - conda-package-streaming=0.12.0
  - contourpy=1.3.3
  - coreutils=9.5
  - cpp-expected=1.1.0
  - cryptography=46.0.3
  - cuda-version=12.9
  - curl=8.16.0
  - cutadapt=5.2
  - cycler=0.12.1
  - dbus=1.16.2
  - decorator=5.2.1
  - defusedxml=0.7.1
  - dnaio=1.2.2
  - dnapi=1.1
  - entrez-direct=22.4
  - executing=2.2.1
  - expat=2.7.3
  - fastp=1.1.0
  - fastqc=0.12.1
  - fftw=3.3.10
  - fmt=10.2.1
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.2
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.61.1
  - freetype=2.14.1
  - fribidi=1.0.16
  - gcc_impl_linux-64=11.2.0
  - gcc_linux-64=11.2.0
  - gettext=0.25.1
  - gettext-tools=0.25.1
  - gfortran_impl_linux-64=11.2.0
  - gfortran_linux-64=11.2.0
  - giflib=5.2.2
  - glib=2.84.2
  - glib-tools=2.84.2
  - graphite2=1.3.14
  - gromacs=2025.4
  - gsl=2.7
  - gxx_impl_linux-64=11.2.0
  - gxx_linux-64=11.2.0
  - h11=0.16.0
  - harfbuzz=9.0.0
  - hdf5=1.14.3
  - hisat2=2.2.2
  - html5lib=1.1
  - htseq=2.0.9
  - htslib=1.21
  - httpcore=1.0.9
  - httpx=0.28.1
  - icu=73.2
  - idna=3.11
  - ipython_pygments_lexers=1.1.1
  - isa-l=2.31.1
  - jansson=2.14
  - jedi=0.19.2
  - jinja2=3.1.6
  - joblib=1.5.3
  - jpeg=9f
  - jsonpatch=1.33
  - jsonpointer=3.0.0
  - jsonschema-specifications=2025.9.1
  - jupyter_client=8.8.0
  - jupyter_core=5.9.1
  - jupyter_events=0.12.0
  - jupyter_server=2.17.0
  - jupyter_server_terminals=0.5.3
  - jupyterlab_pygments=0.3.0
  - jupyterlab_server=2.28.0
  - k8=0.2.5
  - kernel-headers_linux-64=4.18.0
  - keyutils=1.6.3
  - kiwisolver=1.4.9
  - krb5=1.20.1
  - lcms2=2.17
  - ld_impl_linux-64=2.40
  - lerc=4.0.0
  - libaec=1.1.5
  - libarchive=3.6.2
  - libasprintf=0.25.1
  - libasprintf-devel=0.25.1
  - libblas=3.9.0
  - libboost=1.84.0
  - libbrotlicommon=1.2.0
  - libbrotlidec=1.2.0
  - libbrotlienc=1.2.0
  - libcblas=3.9.0
  - libcups=2.3.3
  - libcurl=8.16.0
  - libdeflate=1.22
  - libedit=3.1.20230828
  - libev=4.33
  - libexpat=2.7.3
  - libffi=3.4.4
  - libgcc=15.2.0
  - libgcc-devel_linux-64=11.2.0
  - libgcc-ng=15.2.0
  - libgettextpo=0.25.1
  - libgettextpo-devel=0.25.1
  - libgfortran=15.2.0
  - libgfortran-ng=15.2.0
  - libgfortran5=15.2.0
  - libglib=2.84.2
  - libgomp=15.2.0
  - libhwloc=2.12.1
  - libiconv=1.18
  - libidn2=2.3.8
  - libkrb5=1.21.3
  - liblapack=3.9.0
  - liblzma=5.8.2
  - liblzma-devel=5.8.2
  - libmamba=1.5.1
  - libmambapy=1.5.1
  - libnghttp2=1.58.0
  - libnsl=2.0.1
  - libopenblas=0.3.30
  - libopenssl-static=3.6.1
  - libpng=1.6.54
  - libsodium=1.0.20
  - libsolv=0.7.29
  - libsqlite=3.46.0
  - libssh2=1.11.1
  - libstdcxx=15.2.0
  - libstdcxx-devel_linux-64=11.2.0
  - libstdcxx-ng=15.2.0
  - libtiff=4.7.1
  - libunistring=1.3
  - libuuid=2.41.3
  - libuv=1.51.0
  - libwebp-base=1.6.0
  - libxcb=1.17.0
  - libxcrypt=4.4.36
  - libxgboost=1.7.6
  - libxml2=2.13.9
  - libzlib=1.2.13
  - lmdb=0.9.31
  - lz4-c=1.9.4
  - lzo=2.10
  - make=4.2.1
  - mamba=1.5.1
  - mapseq=2.1.1b
  - matplotlib-base=3.10.1
  - matplotlib-inline=0.2.1
  - mdtraj=1.10.0
  - minimap2=2.28
  - mirdeep2=2.0.1.3
  - munkres=1.0.7
  - mysql-connector-c=6.1.11
  - nbconvert-core=7.16.6
  - nbformat=5.10.4
  - ncbi-datasets-cli=18.16.0
  - ncbi-vdb=3.3.0
  - nccl=2.29.2.1
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - nlohmann_json=3.11.3
  - nlohmann_json-abi=3.12.0
  - nomkl=1.0
  - notebook-shim=0.2.4
  - numexpr=2.14.1
  - ocl-icd=2.3.3
  - opencl-headers=2025.06.13
  - openjdk=11.0.1
  - openjpeg=2.5.2
  - openssl=3.6.1
  - ossuuid=1.6.2
  - overrides=7.7.0
  - packaging=25.0
  - pandas=2.3.3
  - pandoc=3.8
  - pandocfilters=1.5.1
  - pango=1.54.0
  - parso=0.8.5
  - pbzip2=1.1.13
  - pcre2=10.42
  - perl=5.22.0.1
  - perl-archive-tar=2.18
  - perl-common-sense=3.74
  - perl-compress-raw-zlib=2.069
  - perl-encode-locale=1.05
  - perl-exporter-tiny=0.042
  - perl-font-ttf=1.05
  - perl-io-string=1.08
  - perl-json=2.90
  - perl-json-xs=2.34
  - perl-list-moreutils=0.413
  - perl-lwp-simple=6.15
  - perl-pdf-api2=2.025
  - perl-threaded=5.32.1
  - perl-uri=1.71
  - perl-xml-libxml=2.0124
  - perl-xml-namespacesupport=1.11
  - perl-xml-parser=2.44
  - perl-xml-sax=0.99
  - perl-xml-sax-base=1.08
  - pexpect=4.9.0
  - pigz=2.8
  - pip=25.3
  - pixman=0.46.4
  - plink=1.90b7.7
  - pluggy=1.6.0
  - prody=2.6.1
  - prometheus_client=0.21.1
  - prompt-toolkit=3.0.52
  - prompt_toolkit=3.0.52
  - pthread-stubs=0.3
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - py-cpuinfo=9.0.0
  - py-xgboost=1.7.6
  - pybind11-abi=4
  - pycosat=0.6.6
  - pygments=2.19.2
  - pyopenssl=25.3.0
  - pysam=0.23.3
  - pysocks=1.7.1
  - pytables=3.9.2
  - python=3.11.9
  - python-dateutil=2.9.0post0
  - python-fastjsonschema=2.21.2
  - python-isal=1.8.0
  - python-json-logger=4.0.0
  - python-tzdata=2025.3
  - python-zlib-ng=0.4.3
  - python_abi=3.11
  - pytz=2025.2
  - pyyaml=6.0.3
  - pyzmq=27.1.0
  - qhull=2020.2
  - r-askpass=1.2.1
  - r-assertthat=0.2.1
  - r-backports=1.5.0
  - r-base=4.3.1
  - r-base64enc=0.1_3
  - r-bit=4.6.0
  - r-bit64=4.6.0_1
  - r-blob=1.2.4
  - r-boot=1.3_32
  - r-broom=1.0.9
  - r-bslib=0.9.0
  - r-cachem=1.1.0
  - r-callr=3.7.6
  - r-caret=6.0_94
  - r-cellranger=1.1.0
  - r-class=7.3_23
  - r-cli=3.6.5
  - r-clipr=0.8.0
  - r-clock=0.7.3
  - r-cluster=2.1.8.1
  - r-codetools=0.2_20
  - r-colorspace=2.1_1
  - r-commonmark=2.0.0
  - r-conflicted=1.2.0
  - r-cpp11=0.5.2
  - r-crayon=1.5.3
  - r-crul=1.6.0
  - r-curl=7.0.0
  - r-data.table=1.15.2
  - r-dbi=1.2.3
  - r-dbplyr=2.5.1
  - r-diagram=1.6.5
  - r-digest=0.6.37
  - r-dplyr=1.1.4
  - r-dtplyr=1.3.2
  - r-e1071=1.7_16
  - r-ellipsis=0.3.2
  - r-essentials=4.3
  - r-evaluate=1.0.5
  - r-fansi=1.0.6
  - r-farver=2.1.2
  - r-fastmap=1.2.0
  - r-fontawesome=0.5.3
  - r-forcats=1.0.0
  - r-foreach=1.5.2
  - r-foreign=0.8_90
  - r-formatr=1.14
  - r-fs=1.6.6
  - r-future=1.67.0
  - r-future.apply=1.20.0
  - r-gargle=1.6.0
  - r-generics=0.1.4
  - r-ggplot2=3.5.2
  - r-gistr=0.9.0
  - r-glmnet=4.1_10
  - r-globals=0.18.0
  - r-glue=1.8.0
  - r-googledrive=2.1.2
  - r-googlesheets4=1.1.2
  - r-gower=1.0.1
  - r-gtable=0.3.6
  - r-hardhat=1.4.2
  - r-haven=2.5.4
  - r-hexbin=1.28.5
  - r-highr=0.11
  - r-hms=1.1.3
  - r-htmltools=0.5.8.1
  - r-htmlwidgets=1.6.4
  - r-httpcode=0.3.0
  - r-httpuv=1.6.15
  - r-httr=1.4.7
  - r-ids=1.0.1
  - r-ipred=0.9_15
  - r-irdisplay=1.1
  - r-irkernel=1.3.2
  - r-isoband=0.2.7
  - r-iterators=1.0.14
  - r-jquerylib=0.1.4
  - r-jsonlite=2.0.0
  - r-kernsmooth=2.23_26
  - r-knitr=1.50
  - r-labeling=0.4.3
  - r-later=1.4.4
  - r-lattice=0.22_7
  - r-lava=1.8.1
  - r-lazyeval=0.2.2
  - r-lifecycle=1.0.4
  - r-listenv=0.9.1
  - r-lobstr=1.1.2
  - r-lubridate=1.9.4
  - r-magrittr=2.0.3
  - r-maps=3.4.3
  - r-mass=7.3_60.0.1
  - r-matrix=1.6_5
  - r-memoise=2.0.1
  - r-mgcv=1.9_3
  - r-mime=0.13
  - r-modelmetrics=1.2.2.2
  - r-modelr=0.1.11
  - r-munsell=0.5.1
  - r-nlme=3.1_168
  - r-nnet=7.3_20
  - r-numderiv=2016.8_1.1
  - r-openssl=2.3.3
  - r-parallelly=1.45.1
  - r-pbdzmq=0.3_14
  - r-pillar=1.11.0
  - r-pkgconfig=2.0.3
  - r-plyr=1.8.9
  - r-prettyunits=1.2.0
  - r-proc=1.19.0.1
  - r-processx=3.8.6
  - r-prodlim=2025.04.28
  - r-progress=1.2.3
  - r-progressr=0.15.1
  - r-promises=1.3.3
  - r-proxy=0.4_27
  - r-pryr=0.1.6
  - r-ps=1.9.1
  - r-purrr=1.1.0
  - r-quantmod=0.4.28
  - r-r6=2.6.1
  - r-ragg=1.2.6
  - r-randomforest=4.7_1.2
  - r-rappdirs=0.3.3
  - r-rbokeh=0.5.2
  - r-rcolorbrewer=1.1_3
  - r-rcpp=1.1.0
  - r-rcppeigen=0.3.4.0.2
  - r-readr=2.1.5
  - r-readxl=1.4.5
  - r-recipes=1.3.1
  - r-recommended=4.3
  - r-rematch=2.0.0
  - r-rematch2=2.1.2
  - r-repr=1.1.7
  - r-reprex=2.1.1
  - r-reshape2=1.4.4
  - r-rlang=1.1.6
  - r-rmarkdown=2.29
  - r-rpart=4.1.24
  - r-rstudioapi=0.17.1
  - r-rvest=1.0.5
  - r-sass=0.4.10
  - r-scales=1.4.0
  - r-selectr=0.4_2
  - r-shape=1.4.6.1
  - r-shiny=1.11.1
  - r-sourcetools=0.1.7_1
  - r-sparsevctrs=0.3.4
  - r-spatial=7.3_18
  - r-squarem=2021.1
  - r-stringi=1.8.4
  - r-stringr=1.5.2
  - r-survival=3.8_3
  - r-sys=3.4.3
  - r-systemfonts=1.2.1
  - r-textshaping=0.4.0
  - r-tibble=3.3.0
  - r-tidyr=1.3.1
  - r-tidyselect=1.2.1
  - r-tidyverse=2.0.0
  - r-timechange=0.3.0
  - r-timedate=4041.110
  - r-tinytex=0.57
  - r-triebeard=0.4.1
  - r-ttr=0.24.4
  - r-tzdb=0.5.0
  - r-urltools=1.7.3.1
  - r-utf8=1.2.6
  - r-uuid=1.2_1
  - r-vctrs=0.6.5
  - r-viridislite=0.4.2
  - r-vroom=1.6.5
  - r-withr=3.0.2
  - r-xfun=0.53
  - r-xml2=1.3.6
  - r-xtable=1.8_4
  - r-xts=0.14.1
  - r-yaml=2.3.10
  - r-zoo=1.8_14
  - randfold=2.0.1
  - readline=8.3
  - reproc=14.2.5.post0
  - reproc-cpp=14.2.5.post0
  - requests=2.32.5
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rpsbproc=0.5.0
  - ruamel.yaml=0.17.40
  - ruamel.yaml.clib=0.2.15
  - samtools=1.21
  - scikit-learn=1.8.0
  - sed=4.9
  - seqkit=2.12.0
  - seqtk=1.4
  - setuptools=80.10.1
  - simdjson=3.12.3
  - six=1.17.0
  - snappy=1.2.2
  - sniffio=1.3.1
  - spdlog=1.14.1
  - sqlite=3.51.1
  - sra-tools=3.2.1
  - stack_data=0.6.3
  - stringtie=2.2.3
  - sysroot_linux-64=2.28
  - tbb=2022.3.0
  - terminado=0.18.1
  - threadpoolctl=3.6.0
  - tinycss2=1.4.0
  - tk=8.6.15
  - tktable=2.10
  - toolz=1.1.0
  - tornado=6.5.4
  - tqdm=4.67.1
  - traitlets=5.14.3
  - trimmomatic=0.40
  - typing-extensions=4.15.0
  - typing_extensions=4.15.0
  - tzdata=2025c
  - ucsc-liftover=469
  - unicodedata2=17.0.0
  - urllib3=2.6.3
  - viennarna=2.4.7
  - vina=1.2.6
  - vsearch=2.29.1
  - wget=1.25.0
  - wheel=0.46.3
  - xgboost=1.7.6
  - xopen=2.0.2
  - xorg-libice=1.1.2
  - xorg-libsm=1.2.6
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.6
  - xorg-libxfixes=6.0.2
  - xorg-libxi=1.8.2
  - xorg-libxrender=0.9.12
  - xorg-libxt=1.3.1
  - xorg-libxtst=1.2.5
  - xorg-xorgproto=2024.1
  - xz=5.8.2
  - xz-gpl-tools=5.8.2
  - xz-tools=5.8.2
  - yaml=0.2.5
  - yaml-cpp=0.7.0
  - zeromq=4.3.5
  - zlib=1.2.13
  - zlib-ng=2.0.7
  - zstd=1.5.6
  - pip:
      - aiofiles==24.1.0
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.3
      - aiosignal==1.4.0
      - anndata==0.10.9
      - annotated-doc==0.0.4
      - annotated-types==0.7.0
      - anthropic==0.76.0
      - anyio==4.12.1
      - array-api-compat==1.13.0
      - arrow==1.4.0
      - asttokens==3.0.1
      - async-lru==2.1.0
      - authlib==1.6.6
      - backports-tarfile==1.2.0
      - beartype==0.22.9
      - beautifulsoup4==4.14.3
      - brotli==1.2.0
      - cachetools==6.2.5
      - click==8.3.1
      - cloudpickle==3.1.2
      - cyclopts==4.5.1
      - dataclasses-json==0.6.7
      - debugpy==1.8.19
      - diskcache==5.6.3
      - distro==1.9.0
      - dnspython==2.8.0
      - docstring-parser==0.17.0
      - docutils==0.22.4
      - donfig==0.8.1.post1
      - email-validator==2.3.0
      - exceptiongroup==1.3.1
      - fakeredis==2.33.0
      - fastapi==0.128.0
      - fastmcp==2.14.4
      - ffmpy==1.0.0
      - filelock==3.20.3
      - filetype==1.2.0
      - fqdn==1.5.1
      - freesasa==2.2.1
      - frozenlist==1.8.0
      - fsspec==2026.1.0
      - geoparse==2.0.4
      - google-auth==2.48.0
      - google-crc32c==1.8.0
      - google-genai==1.60.0
      - gradio==6.4.0
      - gradio-client==2.0.3
      - graphql-core==3.2.7
      - greenlet==3.3.1
      - groovy==0.1.2
      - h5py==3.15.1
      - hf-xet==1.2.0
      - httpx-sse==0.4.3
      - huggingface-hub==1.3.4
      - igraph==1.0.0
      - importlib-metadata==8.7.1
      - iniconfig==2.3.0
      - ipykernel==7.1.0
      - ipython==9.9.0
      - ipywidgets==8.1.8
      - isoduration==20.11.0
      - jaraco-classes==3.4.0
      - jaraco-context==6.1.0
      - jaraco-functools==4.4.0
      - jeepney==0.9.0
      - jiter==0.12.0
      - json5==0.13.0
      - jsonref==1.1.0
      - jsonschema==4.26.0
      - jsonschema-path==0.3.4
      - jupyter==1.1.1
      - jupyter-console==6.6.3
      - jupyter-lsp==2.3.0
      - jupyter-server-terminals==0.5.4
      - jupyterlab==4.5.3
      - jupyterlab-widgets==3.0.16
      - keyring==25.7.0
      - langchain==0.3.27
      - langchain-anthropic==0.3.22
      - langchain-classic==1.0.1
      - langchain-community==0.4.1
      - langchain-core==1.2.7
      - langchain-deepseek==1.0.1
      - langchain-experimental==0.4.1
      - langchain-google-genai==4.2.0
      - langchain-ollama==0.3.10
      - langchain-openai==1.1.7
      - langchain-text-splitters==1.1.0
      - langchain-xai==1.2.2
      - langgraph==0.3.18
      - langgraph-checkpoint==2.1.2
      - langgraph-prebuilt==0.1.8
      - langgraph-sdk==0.1.74
      - langsmith==0.6.5
      - lark==1.3.1
      - legacy-api-wrap==1.5
      - leidenalg==0.11.0
      - llvmlite==0.46.0
      - lupa==2.6
      - lxml==6.0.2
      - markdown-it-py==4.0.0
      - markupsafe==3.0.3
      - marshmallow==3.26.2
      - matplotlib==3.10.8
      - mcp==1.26.0
      - mdurl==0.1.2
      - mistune==3.2.0
      - more-itertools==10.8.0
      - multidict==6.7.1
      - mypy-extensions==1.1.0
      - natsort==8.4.0
      - nbclient==0.10.4
      - networkx==3.6.1
      - nltk==3.9.2
      - notebook==7.5.3
      - numba==0.63.1
      - numcodecs==0.16.5
      - numpy==2.3.0
      - ollama==0.6.1
      - openai==2.15.0
      - openapi-pydantic==0.5.1
      - opentelemetry-api==1.39.1
      - opentelemetry-exporter-prometheus==0.60b1
      - opentelemetry-instrumentation==0.60b1
      - opentelemetry-sdk==1.39.1
      - opentelemetry-semantic-conventions==0.60b1
      - orjson==3.11.5
      - ormsgpack==1.12.2
      - pathable==0.4.4
      - pathvalidate==3.3.1
      - patsy==1.0.2
      - pdfminer-six==20251230
      - pdfplumber==0.11.9
      - pebble==5.2.0
      - pillow==12.1.0
      - platformdirs==4.5.1
      - prometheus-client==0.24.1
      - propcache==0.4.1
      - psutil==7.2.1
      - py-key-value-aio==0.3.0
      - py-key-value-shared==0.3.0
      - pyasn1==0.6.2
      - pyasn1-modules==0.4.2
      - pycparser==3.0
      - pydantic==2.12.5
      - pydantic-core==2.41.5
      - pydantic-settings==2.12.0
      - pydocket==0.16.6
      - pydub==0.25.1
      - pyjwt==2.10.1
      - pymupdf==1.26.7
      - pynndescent==0.6.0
      - pyparsing==3.3.2
      - pypdf==6.6.2
      - pypdf2==3.0.1
      - pypdfium2==5.3.0
      - pyperclip==1.11.0
      - pytesseract==0.3.13
      - pytest==9.0.2
      - python-dotenv==1.2.1
      - python-multipart==0.0.22
      - rdkit==2025.9.4
      - redis==7.1.0
      - referencing==0.36.2
      - regex==2026.1.15
      - requests-toolbelt==1.0.0
      - rfc3987-syntax==1.1.0
      - rich==14.3.1
      - rich-rst==1.3.2
      - rpds-py==0.30.0
      - rpy2==3.6.4
      - rpy2-rinterface==3.6.3
      - rpy2-robjects==3.6.3
      - rsa==4.9.1
      - safehttpx==0.1.7
      - safetensors==0.7.0
      - scanpy==1.11.5
      - scipy==1.16.3
      - seaborn==0.13.2
      - secretstorage==3.5.0
      - semantic-version==2.10.0
      - send2trash==2.1.0
      - sentencepiece==0.2.1
      - session-info2==0.4
      - shellingham==1.5.4
      - sortedcontainers==2.4.0
      - soupsieve==2.8.3
      - sqlalchemy==2.0.46
      - sse-starlette==3.2.0
      - starlette==0.50.0
      - statsmodels==0.14.6
      - tenacity==9.1.2
      - texttable==1.7.0
      - tiktoken==0.12.0
      - tokenizers==0.22.2
      - tomlkit==0.13.3
      - tooluniverse==0.2.0
      - transformers==5.0.0
      - typer==0.21.1
      - typer-slim==0.21.1
      - typing-inspect==0.9.0
      - typing-inspection==0.4.2
      - tzlocal==5.3.1
      - umap-learn==0.5.11
      - uri-template==1.3.0
      - uuid-utils==0.14.0
      - uvicorn==0.40.0
      - wcwidth==0.5.0
      - webcolors==25.10.0
      - webencodings==0.5.1
      - websocket-client==1.9.0
      - websockets==15.0.1
      - widgetsnbextension==4.0.15
      - wrapt==1.17.3
      - yarl==1.22.0
      - zarr==3.1.5
      - zipp==3.23.0
      - zstandard==0.25.0
prefix: /root/miniconda3/envs/biomni_e1
